// app/layout.tsx
import React from "react";
import Header from "./components/header";
import Footer from "./components/footer";
import "./globals.css"; // Import global styles

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children, //it is a special prop that is automatically passed to components that are used as layouts in Next.js. It represents the content that will be rendered within the layout.
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <Header />
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <Footer />
        </footer>
      </body>
    </html>
  );
}
